#!/bin/bash

set -e

# FIXME Is it safe to remove userand group on removal, or is it owning
# any files?
if false && getent passwd wmbusmeters >/dev/null; then
    userdel wmbusmetersq
    echo user: removed wmbusmeters
fi
if false && getent group wmbusmeters >/dev/null; then
    groupdel wmbusmeters
    echo group: removed wmbusmeters
fi

# Automatically added by dh_installsystemd/13.6ubuntu1
if [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.6ubuntu1
if [ "$1" = "remove" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper mask 'wmbusmeters.service' >/dev/null || true
	fi
fi

if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'wmbusmeters.service' >/dev/null || true
		deb-systemd-helper unmask 'wmbusmeters.service' >/dev/null || true
	fi
fi
# End automatically added section

