name: Build MacOSX
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v2
    - id: INSTALL_ADDITIONAL_BUILD_DEPENDENCIES
      run: brew install librtlsdr libusb
    - id: CONFIGURE
      run: ./configure
    - id: MAKE
      run: make
    - id: TEST
      run: make test
